name: Deploy CloudNest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Deploy CloudNest
        run: |
          cd /home/saif/cloudnest

          git fetch origin
          git reset --hard origin/main

          cd backend
          npm install

          pm2 restart cloudnest-backend || pm2 start src/server.js --name cloudnest-backend

          cd ../frontend
          npm install

          echo "✅ CloudNest deployed successfully!"